server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: bp_editor
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bp_editor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
