// Code generated by dtomapper -type=JobMapper; DO NOT EDIT.

package mapper

import (
	"api/internal/api/handler/request"
	"api/internal/api/handler/response"
	"api/internal/api/models"
)

// JobMapperImpl implements JobMapper
type JobMapperImpl struct{}

// NewJobMapper creates a new instance of JobMapperImpl
func NewJobMapper() JobMapper {
	return &JobMapperImpl{}
}

// CreateJob  Request mapping
func (mapper *JobMapperImpl) CreateJob(req request.CreateJob) models.Job {
	var result models.Job
	result.Name = req.Name
	result.Description = req.Description
	result.FilePath = req.FilePath
	result.OutputPath = req.OutputPath
	result.Active = req.Active
	result.Visibility = req.Visibility
	// TODO: Handle slice field SharedWith manually (element struct not found: uint -> User)
	return result

}

// PatchJob  patch
func (mapper *JobMapperImpl) PatchJob(req request.UpdateJob) map[string]any {
	result := make(map[string]any)
	if req.Name != nil {
		result["name"] = *req.Name
	}
	if req.Description != nil {
		result["description"] = *req.Description
	}
	if req.FilePath != nil {
		result["file_path"] = *req.FilePath
	}
	if req.OutputPath != nil {
		result["output_path"] = *req.OutputPath
	}
	if req.Active != nil {
		result["active"] = *req.Active
	}
	if req.Visibility != nil {
		result["visibility"] = *req.Visibility
	}
	// TODO: Handle slice field SharedWith manually
	// TODO: Handle slice field Nodes manually
	return result

}

// ToJobResponses  Response mapping (simple, without nodes)
func (mapper *JobMapperImpl) ToJobResponses(entities []models.Job) []response.Job {
	result := make([]response.Job, len(entities))
	for i, item := range entities {
		result[i] = mapper.ToJobResponse(item)
	}
	return result

}

// ToJobResponse
func (mapper *JobMapperImpl) ToJobResponse(j models.Job) response.Job {
	var result response.Job
	result.ID = j.ID
	result.Name = j.Name
	result.Description = j.Description
	result.FilePath = j.FilePath
	result.CreatorID = j.CreatorID
	result.Active = j.Active
	result.Visibility = j.Visibility
	result.OutputPath = j.OutputPath
	result.CreatedAt = j.CreatedAt
	result.UpdatedAt = j.UpdatedAt
	//if len(j.Nodes) > 0 {
	//	result.Nodes = make([]Node, len(j.Nodes))
	//	copy(result.Nodes, j.Nodes)
	//}
	//if len(j.SharedWith) > 0 {
	//	result.SharedWith = make([]User, len(j.SharedWith))
	//	copy(result.SharedWith, j.SharedWith)
	//}
	return result

}
