// Code generated by dtomapper -type=MetadataMapper; DO NOT EDIT.

package mapper

import (
	"api/internal/api/handler/response"
	"api/internal/api/models"
)

// MetadataMapperImpl implements MetadataMapper
type MetadataMapperImpl struct{}

func (m MetadataMapperImpl) ToMetadataResponses(entities []models.MetadataDatabase) []response.Metadata {
	//TODO implement me
	panic("implement me")
}

func (m MetadataMapperImpl) ToMetadataResponse(mo models.MetadataDatabase) response.Metadata {
	//TODO implement me
	panic("implement me")
}

// NewMetadataMapper creates a new instance of MetadataMapperImpl
func NewMetadataMapper() MetadataMapper {
	return &MetadataMapperImpl{}
}

