// Code generated by dtomapper -type=NodeMapper; DO NOT EDIT.

package mapper

import (
	"api/internal/api/handler/request"
	"api/internal/api/models"
)

// NodeMapperImpl implements NodeMapper
type NodeMapperImpl struct{}

// NewNodeMapper creates a new instance of NodeMapperImpl
func NewNodeMapper() NodeMapper {
	return &NodeMapperImpl{}
}

// GuessSchemaRequestToDBInputConfig
func (mapper *NodeMapperImpl) GuessSchemaRequestToDBInputConfig(req request.GuessSchemaRequest) models.DBInputConfig {
	var result models.DBInputConfig
	result.Query = req.Query
	result.DbSchema = req.DbSchema
	return result

}
