// Code generated by dtomapper -type=UserMapper; DO NOT EDIT.

package mapper

import (
	"api/internal/api/handler/request"
	"api/internal/api/handler/response"
	"api/internal/api/models"
)

// UserMapperImpl implements UserMapper
type UserMapperImpl struct{}

// NewUserMapper creates a new instance of UserMapperImpl
func NewUserMapper() UserMapper {
	return &UserMapperImpl{}
}

// DtoToUpdate  --update
func (mapper *UserMapperImpl) DtoToUpdate(req request.UpdateUser, vehicle *models.User) {
	if req.Email != nil {
		vehicle.Email = *req.Email
	}
	if req.Prenom != nil {
		vehicle.Prenom = *req.Prenom
	}
	if req.Nom != nil {
		vehicle.Nom = *req.Nom
	}
	if req.Actif != nil {
		vehicle.Actif = *req.Actif
	}

}

// EntityToUserResponse
func (mapper *UserMapperImpl) EntityToUserResponse(user models.User) response.UserResponseDTO {
	var result response.UserResponseDTO
	result.ID = user.ID
	result.Email = user.Email
	result.Prenom = user.Prenom
	result.Nom = user.Nom
	result.Actif = user.Actif
	return result

}
